# Generated by Django 4.1.7 on 2023-02-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='customergroup',
            table='customer_group',
        ),
        migrations.AlterModelTable(
            name='customergroupaddresses',
            table='customer_group_addresses',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
